@echo off
echo Killing stupidlist instances...
powershell -Command "Get-Process electron -ErrorAction SilentlyContinue | Where-Object { $_.Path -like '*stupidlist*' } | Stop-Process -Force" >nul 2>&1
timeout /t 2 /nobreak >nul
echo Building...
call npm run build
echo Launching...
start "" npx electron .
